CATEGORIES = [
    "Shoot 'Em Up",
    # "Time Travel",
    # "Controller",
    # "Drama",
    # "Tanks",
    # "Historical",
    # "Quick-Time Events",
    # "Psychological Horror",
    # "Cartoony",
    # "World War II",
    # "Cute",
    "Strategy",
    # "Dragons",
    # "Mature",
    # "VR",
    # "Survival Horror",
    "Action RPG",
    "Arena Shooter",
    # "Survival",
    "Hack and Slash",
    # "Choose Your Own Adventure",
    # "Isometric",
    # "Dog",
    "Bowling",
    # "Free to Play",
    # "Comedy",
    # "First-Person",
    # "Satire",
    "Turn-Based Tactics",
    # "Education",
    # "Dark",
    # "Futuristic",
    "Tactical RPG",
    # "Flight",
    "Visual Novel",
    "Character Action Game",
    "FMV",
    # "Gore",
    # "Stealth",
    # "Co-op Campaign",
    "Building",
    # "Animation & Modeling",
    "Bullet Hell",
    "Pinball",
    # "Medieval",
    # "Class-Based",
    # "Unforgiving",
    # "Lovecraftian",
    # "Political",
    "Point & Click",
    # "Online Co-Op",
    # "Horror",
    # "Underwater",
    # "Third Person",
    # "Post-apocalyptic",
    "Top-Down Shooter",
    # "Gothic",
    # "Economy",
    # "Hand-drawn",
    # "Competitive",
    # "Masterpiece",
    # "TrackIR",
    # "4 Player Local",
    # "Stylized",
    # "Cinematic",
    "RPG",
    # "Surreal",
    # "Science",
    # "God Game",
    # "Blood",
    # "Memes",
    # "Action-Adventure",
    # "Difficult",
    # "Resource Management",
    "Programming",
    # "NSFW",
    # "Typing",
    # "Cartoon",
    "Driving",
    # "Real-Time",
    # "Co-op",
    # "Cyberpunk",
    # "Family Friendly",
    "City Builder",
    # "Alternate History",
    # "Sci-fi",
    # "Dark Humor",
    # "Military",
    "Turn-Based Strategy",
    # "Aliens",
    # "Addictive",
    # "Superhero",
    "Third-Person Shooter",
    # "Story Rich",
    "Tower Defense",
    # "Touch-Friendly",
    # "Fast-Paced",
    # "Inventory Management",
    # "Dark Fantasy",
    # "Diplomacy",
    "MMORPG",
    # "Crime",
    "Walking Simulator",
    "Simulation",
    # "Romance",
    # "Magic",
    # "Arcade",
    "Exploration",
    "Racing",
    # "Cold War",
    "Metroidvania",
    # "Sexual Content",
    # "Action",
    "Hacking",
    "Platformer",
    "MOBA",
    "Dating Sim",
    # "Trading",
    # "Cats",
    # "LGBTQ +",
    # "Politics",
    "Puzzle-Platformer",
    # "Illuminati",
    # "Capitalism",
    # "Real-Time with Pause",
    # "Old School",
    # "Mod",
    # "Tactical",
    "Strategy RPG",
    # "Voxel",
    "Board Game",
    # "Singleplayer",
    # "eSports",
    # "Souls-like",
    # "Vampire",
    # "2D",
    # "Heist",
    # "Swordplay",
    # "Minimalist",
    # "4X",
    # "Moddable",
    # "Episodic",
    # "Realistic",
    "2D Fighter",
    # "Faith",
    # "Villain Protagonist",
    # "Classic",
    # "Games Workshop",
    # "Parkour",
    # "Choices Matter",
    "FPS",
    "Shooter",
    "Grand Strategy",
    # "Dystopian",
    # "Epic",
    # "Linear",
    # "Comic Book",
    # "Nudity",
    "Beat 'em up",
    "Fighting",
    # "Steampunk",
    # "Multiple Endings",
    # "Parody",
    # "Utilities",
    # "Destruction",
    # "War",
    # "Split Screen",
    # "Silent Protagonist",
    # "Dark Comedy",
    # "Retro",
    # "Massively Multiplayer",
    # "Emotional",
    # "Time Manipulation",
    # "Local Co-Op",
    # "Mythology",
    # "Fantasy",
    # "Local Multiplayer",
    # "Sandbox",
    # "Zombies",
    "Soccer",
    # "Game Development",
    # "Side Scroller",
    # "Funny",
    # "Crowdfunded",
    # "Loot",
    # "PvP",
    # "Beautiful",
    # "Philisophical",
    "Turn-Based Combat",
    # "Indie",
    # "1990's",
    # "Management",
    # "Multiplayer",
    # "Kickstarter",
    # "Space",
    "Crafting",
    # "Remake",
    "Puzzle",
    # "Mystery",
    "Clicker",
    # "Female Protagonist",
    # "Casual",
    "Dungeon Crawler",
    # "Top-Down",
    "Battle Royale",
    # "Card Game",
    # "Perma Death",
    # "Football",
    # "Pixel Graphics",
    # "Gun Customization",
    "RTS",
    "JRPG",
    "Adventure",
    # "Great Soundtrack",
    # "Replay Value",
    # "Benchmark",
    # "RPGMaker",
    # "Team-Based",
    # "PvE",
    # "Ninja",
    # "Cult Classic",
    # "Violent",
    # "America",
    # "Atmospheric",
    # "Warhammer 40K",
    # "Time Attack",
    # "Robots",
    # "Turn-Based",
    # "Lore-Rich",
    "Sports",
    # "Physics",
    # "Early Access",
    # "Anime",
    # "Rogue-like",
    # "Base Building",
    # "Short",
    # "Open World",
    # "Character Customization",
]